<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Amit" ignored="0" name="Banking APP Test" tests="6" failures="3" timestamp="2021-02-21T13:14:36 IST" time="101.529" errors="0">
  <testcase name="loginTest" time="4.797" classname="com.inetBanking.testCases.TC_LoginTest_001"/>
  <testcase name="LoginDDT" time="16.124" classname="com.inetBanking.testCases.TC_LoginDDT_002"/>
  <testcase name="LoginDDT" time="7.525" classname="com.inetBanking.testCases.TC_LoginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.testCases.TC_LoginDDT_002.LoginDDT(TC_LoginDDT_002.java:33)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginDDT -->
  <testcase name="LoginDDT" time="8.059" classname="com.inetBanking.testCases.TC_LoginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.testCases.TC_LoginDDT_002.LoginDDT(TC_LoginDDT_002.java:33)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginDDT -->
  <testcase name="LoginDDT" time="7.912" classname="com.inetBanking.testCases.TC_LoginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.testCases.TC_LoginDDT_002.LoginDDT(TC_LoginDDT_002.java:33)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginDDT -->
  <testcase name="addNewCustomer" time="22.83" classname="com.inetBanking.testCases.TC_AddCustomerTest_003"/>
</testsuite> <!-- Banking APP Test -->
